export const skills: Record<string, string[]> = {
  frontend: [
    "HTML",
    "CSS",
    "SCSS",
    "TailwindCSS",
    "RadixUI",
    "Daisy UI",
    "Bootstrap",
    "Javascript",
    "TypeScript",
    "React",
    "Next.js",
    "Framer Motion",
    "GSAP",
    "Zustand",
    "Redux",
    "and more...",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "NestJS",
    "NoSQL",
    "Mongoose",
    "SQL",
    "TypeORM",
    "Socket.IO",
    "and more...",
  ],
  others: ["Git", "RestAPIs", "GraphQL", "and more..."],
};
